3Tier-System-web/src/main/java/ejb/ProductManagedBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ejb;

import entity.ProductEntity;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "product")
@SessionScoped
public class ProductManagedBean implements Serializable{
    @EJB
    private SessionBean sessionBean;
    
    public List<ProductEntity> getProducts() {
        return sessionBean.getProducts();
    }
}

3Tier-System-web/src/main/webapp/order/Create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Create a new Order</title>
        <link type="text/css" rel="stylesheet" href="../style.css" />
    </h:head>
    <h:body>
        <div class="header">
            <h1><h:outputText value="Create a new Order"/></h1>
            <br/>
            </div>
        <f:view>
            <h:form>
                <h:messages style="color:red;margin:8px;" />
                <h:panelGrid columns="2">
                    <h:outputLabel value="Product:" for="product" />
                    <h:selectOneMenu id="product" value="#{order.productId}" title="Product" >
                        <f:selectItems value="#{product.products}" var="_product" itemValue="#{_product.id}" itemLabel="#{_product.title}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="Count:" for="count" />
                    <h:inputText id="count" value="#{order.order.count}" title="Count" />
                    <h:outputLabel value="Customer:" for="customer" />
                    <h:selectOneMenu id="customer" value="#{order.customerId}" title="Customer">
                        <f:selectItems value="#{customer.customers}" var="_customer" itemValue="#{_customer.id}" itemLabel="#{_customer.name}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{order.create()}" value="Create Order" />
                <div class="footer">
                    <h:commandLink action="#{order.prepareList()}" value="Order List" />
                    <h:commandLink action="#{order.mainPage()}" value="Main Page"/>
                </div>
                 <cr>COIT20227: Enterprise Computing. Student ID: s0217325</cr>
                  </h:form>
        </f:view>
    </h:body>
</html>

3Tier-System-web/src/main/webapp/order/Found.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsf/core">
    <h:head>
        <title>The Found Orders</title>
        <link type="text/css" rel="stylesheet" href="../style.css" />
    </h:head>
    <h:body>
        <div class="header">
            <h1><h:outputText value="The Found Orders"/></h1>
            <br/>
             </div>
        <c:view>
            <h:form>
                <h:dataTable value="#{order.foundorders}" var="item" styleClass="table"
                             headerClass="table-header"
                             rowClasses="table-odd-row,table-even-row">
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Id"/>
                        </c:facet>
                        <h:outputText value="#{item.id}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Customer"/>
                        </c:facet>
                        <h:commandLink action="#{customer.prepareViewFromOrderPage(item.customer)}" value="#{item.customer.name}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Item"/>
                        </c:facet>
                        <h:commandLink rendered="#{item.product.type eq 'Book'}" action="#{book.prepareViewFromOrderPage(item.product)}" value="#{item.product.title}"/>
                        <h:commandLink rendered="#{item.product.type eq 'CD'}" action="#{cd.prepareViewFromOrderPage(item.product)}" value="#{item.product.title}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Created at"/>
                        </c:facet>
                        <h:outputText value="#{item.datetime}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Unit Price"/>
                        </c:facet>
                        <h:outputText value="$ #{item.datetime}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Count"/>
                        </c:facet>
                        <h:outputText value="#{item.count}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Total Price"/>
                        </c:facet>
                        <h:outputText value="#{order.totalPrice(item)}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Actions"/>
                        </c:facet>
                        <h:commandLink action="#{order.delete(item)}" value="Delete"/>
                    </h:column>
                </h:dataTable>
                <p>Total: #{order.foundorders.size()}</p>
                <div class="footer">
                    <h:commandLink action="#{order.prepareCreate}" value="Create a new Order"/>
                    <h:commandLink action="#{order.mainPage()}" value="Main Page"/>
                </div>
                 <cr>COIT20227: Enterprise Computing. Student ID: s0217325</cr>
                  </h:form>
        </c:view>
    </h:body>
</html>

3Tier-System-web/src/main/webapp/order/List.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsf/core">
    <h:head>
        <title>List of Orders</title>
        <link type="text/css" rel="stylesheet" href="../style.css" />
    </h:head>
    <h:body>
        <div class="header">
            <h1><h:outputText value="List of Orders"/></h1>
            <br/>
             </div>
        <c:view>
            <h:form>
                <h:messages style="color:blue;margin:8px;" />
                <h:dataTable value="#{order.orders}" var="item" styleClass="table"
                             headerClass="table-header"
                             rowClasses="table-odd-row,table-even-row">
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Id"/>
                        </c:facet>
                        <h:outputText value="#{item.id}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Customer"/>
                        </c:facet>
                        <h:commandLink action="#{customer.prepareViewFromOrderPage(item.customer)}" value="#{item.customer.name}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Item"/>
                        </c:facet>
                        <h:commandLink rendered="#{item.product.type eq 'Book'}" action="#{book.prepareViewFromOrderPage(item.product)}" value="#{item.product.title}"/>
                        <h:commandLink rendered="#{item.product.type eq 'CD'}" action="#{cd.prepareViewFromOrderPage(item.product)}" value="#{item.product.title}"/>
                    </h:column>
                    <h:column>
                        <c:facet name="header">
                            <h:outputText value="Action"/>
                        </c:facet>
                        <h:commandLink action="#{order.delete(item)}" value="Delete"/>
                    </h:column>
                </h:dataTable>
                <p>Total: #{order.orders.size()}</p>
                <div class="footer">
                    <h:commandLink action="#{order.prepareCreate}" value="Create a new Order"/>
                    <h:commandLink action="#{order.mainPage()}" value="Main Page"/>
                </div>
                 <cr>COIT20227: Enterprise Computing. Student ID: s0217325</cr>
                  </h:form>
        </c:view>
    </h:body>
</html>

3Tier-System-web/src/main/webapp/order/Search.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Search for a Order</title>
        <link type="text/css" rel="stylesheet" href="../style.css" />
    </h:head>
    <h:body>
        <div class="header">
            <h1><h:outputText value="Search for a Order"/></h1>
            <br/>
           </div>
        <h:form>
            <h:panelGrid columns="2">
                <h:outputLabel value="Id:" for="id" />
                <h:inputText id="id" value="#{order.searchId}" title="Id" />
            </h:panelGrid>
            <h:commandLink action="#{order.prepareSearch()}" value="Search for a Order" />
            <div class="footer">
                <h:commandLink action="#{order.prepareList()}" value="Order List" />
                <h:commandLink action="#{order.mainPage()}" value="Main Page"/>
            </div>
             <cr>COIT20227: Enterprise Computing. Student ID: s0217325</cr>
              </h:form>
    </h:body>
</html>